### ISSUE TITLE
Input to generator

### ISSUE THREAD

**Issue by tlatkowski** [shepnerd/inpainting_gmcnn#10]
Hi @shepnerd ,

I've analysed your code and I have a question regarding the input to the generator. 
While making the input you concatenate the masked image with mask and matrix of ones. I understand pros of using mask as additional input but what is the intuition behind the usage of one more channel filled with 1?

**Comment by shepnerd** [comment]
That part can be removed if no more conditions are fed in. Besides of just
inpainting a missing region, sometimes we can give more conditions to guide
the generation process, e.g., semantic layout, edge maps. These types of
additional conditions can be added as extra channels of the input. In this
implementation, however, the aforementioned extra conditions are not
utilized.

Tomasz Latkowski <notifications@github.com> 于2019年4月3日周三 下午5:52写道：

**Comment by tlatkowski** [comment]
Great thanks!
