### ISSUE TITLE
not training 

### ISSUE THREAD

**Issue by cuevas1208** [shepnerd/inpainting_gmcnn#11]
When I tried to train it looks like it freezes, i do not see any progress after hours. I am using a 1080ti and i am training with the following command:

python train.py --dataset coco_2014 --data_file /home/jkim/Documents/datasets/coco_2014/ --gpu_ids 0 

![image](https://user-images.githubusercontent.com/13240742/56072355-a3e27080-5d4a-11e9-8a9b-dfcee17b9b4c.png)

**Comment by shepnerd** [comment]
I guess the given data file was invalid. The required parameter data_file
is a file containing image paths, e.g., --data_file
/home/jkim/coco_train.txt and the contents in coco_train.txt are like
/xxx/xxx/xxx.jpg.

Manuel Cuevas <notifications@github.com> 于2019年4月13日周六 上午8:46写道：

**Comment by cuevas1208** [comment]
I use glob to get the file path list (see image bellow). It still gets stuck when I try to train. 
![image](https://user-images.githubusercontent.com/13240742/56150893-c18b2200-5f64-11e9-92dd-138f2b103916.png)

**Comment by shepnerd** [comment]
Using glob to retrieve images works for me. Maybe there were still no valid image paths in self.filelist. Checking the value of self.filelist should be helpful.
