### ISSUE TITLE
The error of training

### ISSUE THREAD

**Issue by MrZealand** [shepnerd/inpainting_gmcnn#17]
I used my dataset "celeba" which contains 1000 images to pretrain the GMCNN in Pycharm, Windows. I set the  "--data_file" as "./imgs/celeba",but the error happened:
![image](https://user-images.githubusercontent.com/37623259/57619796-6d9e4800-75b9-11e9-9374-a66a706513a5.png)

<img width="868" alt="微信图片_20190513195725" src="https://user-images.githubusercontent.com/37623259/57619765-5b240e80-75b9-11e9-951f-dc430b1de653.png">
How should i solve this problem?
Thanks  very much!

**Comment by shepnerd** [comment]
For training, you need to feed a file instead of a directory, e.g.,
./imgs/celeba/train.txt. And that file should contain the full image paths.

剑楠 <notifications@github.com> 于2019年5月13日周一 下午7:59写道：

**Comment by zhangbaijin** [comment]
this is my train error
python train.py --dataset [./dataset/celebahq_256X256] --data_file [./imgs/celebahq_256X256] --gpu_ids [0] --pretrain_network 1 --batch_size 8
and the problem is that:
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    config = TrainOptions().parse()
  File "/media/inpainting_gmcnn-master/pytorch/options/train_options.py", line 74, in parse
    id = int(str_id)
ValueError: invalid literal for int() with base 10: '[0]'

thanks for your time!

**Comment by MrZealand** [comment]
> this is my train error
> python train.py --dataset [./dataset/celebahq_256X256] --data_file [./imgs/celebahq_256X256] --gpu_ids [0] --pretrain_network 1 --batch_size 8
> and the problem is that:
> Traceback (most recent call last):
> File "train.py", line 11, in 
> config = TrainOptions().parse()
> File "/media/inpainting_gmcnn-master/pytorch/options/train_options.py", line 74, in parse
> id = int(str_id)
> ValueError: invalid literal for int() with base 10: '[0]'
> thanks for your time!

do not use "[" and "]"

**Comment by zhangbaijin** [comment]
ok......

**Comment by zhangbaijin** [comment]
你好，问题解决了吗？他说的data_file是什么意思。。。什么train,txt包含/xxx/xxx/xxx.jpg。。。

**Comment by MrZealand** [comment]
解决了啊。data_file就是一个包含了你所有的训练图片地址的txt

发送自 Windows 10 版邮件应用

发件人: zhangbaijin
发送时间: 2019年5月17日 13:45
收件人: shepnerd/inpainting_gmcnn
抄送: 剑楠; Author
主题: Re: [shepnerd/inpainting_gmcnn] The error of training (#17)

你好，问题解决了吗？他说的data_file是什么意思。。。什么train,txt包含/xxx/xxx/xxx.jpg。。。

**Comment by zhangbaijin** [comment]
好咧 谢谢

**Comment by MrZealand** [comment]
你好，请问训练集里的图片应该白色马赛克吗？你的训练集图片是加了白色马赛克的图片吗？

发送自 Windows 10 版邮件应用

发件人: zhangbaijin
发送时间: 2019年5月17日 14:31
收件人: shepnerd/inpainting_gmcnn
抄送: 剑楠; Author
主题: Re: [shepnerd/inpainting_gmcnn] The error of training (#17)

好咧 谢谢

**Comment by shepnerd** [comment]
从三通道uint8精度看，训练时填充区域用的是均值(127.5,127.5,127.5)，而不是白色全255。

剑楠 <notifications@github.com> 于2019年5月18日周六 下午2:20写道：
