### ISSUE TITLE
error of train.py

### ISSUE THREAD

**Issue by zhangbaijin** [shepnerd/inpainting_gmcnn#18]
i just use 20 images for experiment .and train.txt includes 20 images path like /dataset/celeba_256X256/000001.jpg .....dataset/celeba_256X256/0000020.jpg  
![图片](https://user-images.githubusercontent.com/44993660/57906692-66bf5000-78ad-11e9-9e77-697257866ad7.png)

python train.py --dataset [./dataset/celeba_256X256] --data_file [./dataset/train.txt] --gpu_ids [0] --pretrain_network 1 --batch_size 8
and the problem  Traceback (most recent call last):
  File "train.py", line 11, in <module>
    config = TrainOptions().parse()
  File "/media//inpainting_gmcnn-master/pytorch/options/train_options.py", line 74, in parse
    id = int(str_id)
ValueError: invalid literal for int() with base 10: '[0]' 
by the way ,i just have one gpu 1060

**Comment by MrZealand** [comment]
use the following command:
python train.py --dataset celeba --data_file ./dataset/train.txt --gpu_ids 0 --pretrain_network 1 --batch_size 8
