### ISSUE TITLE
Question about the way of calculating PSNR and SSIM

### ISSUE THREAD

**Issue by cmyyy** [shepnerd/inpainting_gmcnn#19]
Hello~
I used the metrics.py of paper"Edge-connect:……" to calculate PSNR and SSIM on validation set of celeba-HQ-256, but the result is different from yours especially on SSIM, so could u share the file used for calculating PSNR and SSIM?

And i want to make clear somethings which need your help:
When i make celeba-HQ-256 dataset from celeba, there is a .zip about delta ,when i used it,there will be noise in the photos,like colorful points in the black area, if not, the photos are clean, how about the celeba-HQ-256 you used? And what's the format（.jpg or .png)? It would be helpful if you share the celeba-HQ-256 dataset.
THX !~

**Comment by shepnerd** [comment]
In the paper, we use psnr and ssim provided in matlab. The used celeba-hq
dataset is shared by jiahui yu as follows:
https://drive.google.com/open?id=1_BsFYYGVvcjcPNhPam2STBDFG3eKAdKr

cmyyy <notifications@github.com> 于2019年5月29日周三 下午11:39写道：

**Comment by cmyyy** [comment]
所以是计算每一对图片(原图和生成图片)的PSNR/SSIM，然后取均值吗？

**Comment by shepnerd** [comment]
是的

cmyyy <notifications@github.com> 于2019年6月3日周一 上午10:04写道：
