### ISSUE TITLE
my own masl

### ISSUE THREAD

**Issue by prerna-grg** [shepnerd/inpainting_gmcnn#2]
Hey @shepnerd 
How can I test your code on my own mask ?

**Comment by shepnerd** [comment]
You can write your own test script by referring the given test.py. Generally, you need to change L54-70 in test.py by loading your own mask. For example, mask = cv2.imread('mask.png'). For the loaded mask, you need to ensure its height and width are the same as that of the test image, its shape is like (h, w, 1), and its values are 0 or 1.
