### ISSUE TITLE
How to continue training?

### ISSUE THREAD

**Issue by darekmm** [shepnerd/inpainting_gmcnn#21]
So how do I carry on a previously stopped training? It seems that if I try to load a previous model it starts with a new folder.

**Comment by shepnerd** [comment]
Using the option '--load_model_dir', then the current training will load the previous model parameters as the initialized ones (the loading message is also shown in the console output). The code just creates a new folder based on the options and time stamp each time when a new training begins (no matter using the previous model or not).

**Comment by darekmm** [comment]
Okay. To be clear: if I load a previous model this way, will it continue to (pre)train it or start from scratch with the same parameters? In other words is it possible to train the model for 3 hours then quit; then continue the training later from the same point?

**Comment by shepnerd** [comment]
It will continue the previous training using the load option.

**Comment by darekmm** [comment]
Okay thank you! Keep up the good work
