### ISSUE TITLE
train the celebaHQ with tensorflow version

### ISSUE THREAD

**Issue by ljjcoder** [shepnerd/inpainting_gmcnn#24]
thanks for your excellent work! when i train the tensorflow version on celebAHQ. I find the train data is crop from the original images not resize. 
![1563156052(1)](https://user-images.githubusercontent.com/40750189/61192537-917c2800-a6e7-11e9-809e-5ee3bbcaca40.png)
could i need to change some parameters to make the training data resize from the original one?

**Comment by shepnerd** [comment]
You could 1. change `tf.image.resize_image_with_crop_or_pad` to `tf.image.resize_image` in ./data/data.py (L22); or 2. create a celebHQ-256x256 dataset before training, and then run code on this new dataset. The latter approach could reduce data loading time relatively at the cost of using more hard disk space.

**Comment by ljjcoder** [comment]
I change the im_gt = tf.image.resize_image_with_crop_or_pad(im_gt, self.im_size[0], self.im_size[1]) to im_gt = tf.image.resize_images(im_gt, self.im_size[0], self.im_size[1]), but the code raise error like this 
![image](https://user-images.githubusercontent.com/40750189/61200763-1af61f00-a715-11e9-9c96-483c2c224789.png)
the changed code like this
![image](https://user-images.githubusercontent.com/40750189/61200823-42e58280-a715-11e9-9698-853e466f227c.png)
is anything wrong?

**Comment by shepnerd** [comment]
Set image shape before using resize_images, like
`im_gt = tf.cast(im_gt, tf.float32)`
`im_gt.set_shape([1024, 1024, 3])`
`im_gt = tf.image.resize_images(im_gt, self.im_size[0], self.im_size[1])`
