### ISSUE TITLE
pretrained model for random mask on celeba-HQ

### ISSUE THREAD

**Issue by csxmli2016** [shepnerd/inpainting_gmcnn#27]
Hi,  can you share the model trained on random mask of celeba? I test the released model (celebahq256_rect) on random mask, the result is really bad. Just shown below.
![input_001](https://user-images.githubusercontent.com/26357039/62426309-a90e6580-b715-11e9-84a0-240cb8e5ba8e.png)
![001](https://user-images.githubusercontent.com/26357039/62426310-ab70bf80-b715-11e9-975c-6c78b11488ef.png)

**Comment by shepnerd** [comment]
https://drive.google.com/open?id=14u58ZEUb6pg5mVwDlUIm6YDjiluqZoBU
It is trained on 512x512 face images with random strokes. We do not have models trained on 256x256 face images with random strokes.

**Comment by csxmli2016** [comment]
Thanks for your kind reply.
