### ISSUE TITLE
question about Figure 6 in the paper

### ISSUE THREAD

**Issue by bearcatt** [shepnerd/inpainting_gmcnn#33]
I read the paper and have a question about the results in Figure 6.
![image](https://user-images.githubusercontent.com/13255692/66016501-7a402000-e509-11e9-9661-805c9cac5160.png)
It seems that the results w/o ID-MRF are better than ID-MRF.

**Comment by bearcatt** [comment]
Is this ID-MRF term really beneficial?

**Comment by shepnerd** [comment]
That's a typo in the paper. Sorry for misleading. The results in (b) are w/o ID-MRF and those in (c) are with ID-MRF. More related examples (Fig. 6 and Fig. 7, P7-8) are given in our [supplementary file](https://drive.google.com/file/d/1uzYgpiCkENTqW-Yy-AriHXH0wUidi3KY/view?usp=sharing).

**Comment by bearcatt** [comment]
@shepnerd Thank you!
