### ISSUE TITLE
The design of upsampling

### ISSUE THREAD

**Issue by WMCh** [shepnerd/inpainting_gmcnn#35]
I notice that you use different strategies to upsample the components. Bilinear is for 7x7 branch, deconvolution is for 3x3 branch and both are used for 5x5 branch. Is there any difference between bilinear and deconvolution? Why do you arrange upsample strategy like this?
Thank you!

**Comment by shepnerd** [comment]
The deconvolution in the framework figure is implemented by the combination of the nearest-neighbor upsampling and convolution, which is a common practice for the learnable upsampling operation. Compared with standard deconvolution, it generates less artifacts usually. For the feature maps produced by different branches, they are upsampled by bilinear, which gives smoother predictions compared with nearest-neighbor upsampling.

**Comment by WMCh** [comment]
Thank you for your reply. But I am not sure if I have made it clear. In other words, why don't you upsample the feature map of 3x3 branch by bilinear interpolation and 7x7 branch by nearest interpolation followed by convolution?

**Comment by shepnerd** [comment]
The visual performance change is marginal for this task when replacing bilinear interpolation with nearest neighbor upsampling or vice verse.
