### ISSUE TITLE
Bad results on 512*680 image

### ISSUE THREAD

**Issue by farazBhatti** [shepnerd/inpainting_gmcnn#37]
Hi , i was testing a random image on 512*680 pretrained model but the results seems to be not reflecting what they should be. Do you have any suggestions on how to improve it? Will they improve if i retrain your  512x680 model using 512x512 images? My assumption is that 256x256 images were used in training 512x680 model(might be wrong, kindly correct) , because when i set input tensor to size 256*256 given the same image (after resizing of-course) for inpainting then results are good.

Image chosen from internet randomly
![img_02](https://user-images.githubusercontent.com/37732181/66893002-81d1ef80-f006-11e9-9828-8e819645add6.png)
 Inpainting results
![oie_KbTS5qcU8rKM](https://user-images.githubusercontent.com/37732181/66893092-b2198e00-f006-11e9-9c13-553597039f2c.png)

inpainting result when input tensor is set to 256*256, on the same resized image
![007](https://user-images.githubusercontent.com/37732181/66893446-8945c880-f007-11e9-98a5-b74abc915943.png)

**Comment by shepnerd** [comment]
Finetuning the network on the 512x512 images should help. Besides, our method still has difficulties dealing with large-scale datasets with thousands of diverse object and scene categories. For your given object-removal like task, [contextual attention](https://github.com/JiahuiYu/generative_inpainting) works well.

**Comment by farazBhatti** [comment]
hmm, so maybe i should fine tune it with 512*512 images. For 'Contextual Attention' doesnt it have custom layers?(but i havent tried converting it) because ultimately i would want to convert trained model into coreml

**Comment by shepnerd** [comment]
I see. Contextual attention does has its own custom layer.

**Comment by farazBhatti** [comment]
So maybe retraining on 512*512 images should fix this problem , I suppose?

**Comment by shepnerd** [comment]
Retraining the model on 512x512 will alleviate the problem but may not fix it. As I mentioned, our model performs unstably on a large-scale dataset with diverse scenes.
