### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by 12-wu** [shepnerd/inpainting_gmcnn#39]
Excuse me,I want to run prtrained models of CelebA-HQ-256,but have a error  as follows :‘
 return files[sorted(range(len(file_times)), key=lambda x: file_times[x])[-1]]
IndexError: list index out of range’  I can't solve it.

**Comment by shepnerd** [comment]
It seems the path of the pretrained model is invalid. You can check the path first.

**Comment by 12-wu** [comment]
![image](https://user-images.githubusercontent.com/57214668/68191318-482f4b80-ffea-11e9-8435-b2ad5c654f70.png)

**Comment by 12-wu** [comment]
thank you very much.I have already run the pretrained model of the celeba-hq-256.but the results are not very well,such as :
![image](https://user-images.githubusercontent.com/57214668/68191569-c986de00-ffea-11e9-9697-7642050dd628.png) 
![image](https://user-images.githubusercontent.com/57214668/68191592-d572a000-ffea-11e9-89c5-b2a511d7a1a7.png)
![image](https://user-images.githubusercontent.com/57214668/68191630-e8857000-ffea-11e9-8e44-4b58660ea06c.png)
![image](https://user-images.githubusercontent.com/57214668/68191652-f63af580-ffea-11e9-83c7-7ac9a9416dd5.png)
![image](https://user-images.githubusercontent.com/57214668/68191688-09e65c00-ffeb-11e9-824c-0ac59e735297.png)
![image](https://user-images.githubusercontent.com/57214668/68191699-1074d380-ffeb-11e9-8366-7f4d08a90909.png)
![image](https://user-images.githubusercontent.com/57214668/68191728-22567680-ffeb-11e9-82ed-152686694e7d.png)
![image](https://user-images.githubusercontent.com/57214668/68191753-313d2900-ffeb-11e9-8165-01b888567758.png)
I think may be the mask size is too large to inpainting well,can you help me  solve it?and make the visual effect of the results better.Thanks again

**Comment by shepnerd** [comment]
Your used testing images are from celeba and the pretrained model is for celeba-hq (with 256 x 256 resolution). It seems the performance of celebahq model would degrade in this case as the differences between these two datasets are not to be neglected. Our pretrained model for celeba will be released at the end of this month.

**Comment by 12-wu** [comment]
Excuse me,I have a problem when I try to train as follows:
![1](https://user-images.githubusercontent.com/57214668/68354509-8b530100-0147-11ea-8dc1-bd92f64a7bf0.png)
![2](https://user-images.githubusercontent.com/57214668/68354521-90b04b80-0147-11ea-89c8-8ed8feed1835.png) 
I help you can help me.thanks a lot

**Comment by shepnerd** [comment]
Refer to #11 .

**Comment by 12-wu** [comment]
I'm so sorry to bother again. I have a problem when I want train such as:
![result](https://user-images.githubusercontent.com/57214668/68556424-2eb85480-046d-11ea-8d60-bd0ba007ed81.png)
but I have tensoflow.layers.and I have install tensorflow again.
this is my command：
![order](https://user-images.githubusercontent.com/57214668/68556559-b2724100-046d-11ea-8a73-f40b8cf8a36c.png).
The whole process is as follows
![all](https://user-images.githubusercontent.com/57214668/68556724-61168180-046e-11ea-9507-fb4f34bf0560.png)
![all2](https://user-images.githubusercontent.com/57214668/68556729-64117200-046e-11ea-94c4-ebbc22485289.png)

**Comment by shepnerd** [comment]
It might be caused the tensorflow version. Please refer to [here](https://github.com/tensorflow/tensorflow/issues/8654).
