### ISSUE TITLE
when will pre train converge

### ISSUE THREAD

**Issue by nywang2019** [shepnerd/inpainting_gmcnn#40]
Hi, I used the pretrained imagenet weights with rect inpainting style to train my dataset (about 4000 images) . here are some hyperparameters: --batch_size 16 --mask_type rect  --lr 1e-4 --train_spe 4000 --max_iters 72000
it seems the train is hard to converge. so what should i do next?  continue to pretrain? how many iters should i train? thanks. see pics below:

![image](https://user-images.githubusercontent.com/55544699/68603907-4268b880-0477-11ea-814b-8867522dc13d.png)
![image](https://user-images.githubusercontent.com/55544699/68603934-544a5b80-0477-11ea-93b4-9dc64758b3cf.png)
![image](https://user-images.githubusercontent.com/55544699/68603972-6a581c00-0477-11ea-903f-5bf35b773526.png)

**Comment by nywang2019** [comment]
i tested some pics with my trained model, the results are not good.

**Comment by shepnerd** [comment]
May I ask about the contents about your dataset? Usually, if the given training dataset is relatively small and contains images with diverse types, the pretraining is hard to converge. In this situation, using a pretrained model is a good option as it can provide necessary generation priors.

**Comment by nywang2019** [comment]
my dataset is about religious mural

**Comment by shepnerd** [comment]
If your religious mural dataset contains portraits, that will be quite challenging. In your case, I guess proper data augmentation (e.g. multi-scale, flip, etc.) or applying some non-parametric methods would help (e.g. attention based layers or methods. They are good at regularizing the ill-posed optimization). From my perspective, learning-based methods relies heavily on the training data, and only perform well when the distribution of testing data is close to the former. When the given training data is complex and diverse, a sufficient training quantity is vital, or using any practical regularizations / priors we induce from the dataset.

**Comment by nywang2019** [comment]
thanks for your kind answer!
