### ISSUE TITLE
Some questions about testing on paris_street

### ISSUE THREAD

**Issue by jfzhuang** [shepnerd/inpainting_gmcnn#43]
Thanks for your excellent work！I have some doubts about testing on paris_street. When I test the image with your realesed trained weight, I found the result is different from that in your published paper.

I used the following command for testing:
python test.py --dataset paris_streetview \
--data_file ./imgs/paris-streetview_256x256/ \
--load_model_dir ./checkpoints/paris-streetview_256x256_rect/ --random_mask 0
![1](https://user-images.githubusercontent.com/20696784/69035307-4fa91880-0a1e-11ea-9250-803a51d3c511.png)

Is there anything I am missing?

**Comment by shepnerd** [comment]
Some released models are trained from stretch using our released code.  We did not fix random seeds in training, so some testing results from the released models are different from that in the paper.

**Comment by jfzhuang** [comment]
Thanks for your quick reply. It helps a lot.
