### ISSUE TITLE
Training with custom images

### ISSUE THREAD

**Issue by xyzdcgan** [shepnerd/inpainting_gmcnn#44]
Hi,

I tested the pre trained model, and results were amazing, 

Can please please tell us how to re-train the model with custom image data set.?
What should be resolution of images.?
And is there any pre processing needed on images before keeping them in training

Thanks @shepnerd

**Comment by shepnerd** [comment]
For training on custom image datasets, you need to generate a file storing all the absolute paths of the training images first (you can refer to [this](https://github.com/shepnerd/inpainting_gmcnn/issues/18#issue-445279694)). The resolution of the training images will be padded or cropped to a fixed size with the training option `--img_shapes`. In our experiments, we set such fixed size as 256x256.

**Comment by xyzdcgan** [comment]
Thanks @shepnerd
