### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by MrLassagna** [shepnerd/inpainting_gmcnn#47]
Following is the full stack trace of the PyTorch version...

C:\inpainting_gmcnn\pytorch>python test.py --dataset paris_streetview --data_file imgs/paris-streetview_256x256/ --load_model_dir checkpoints/paris-streetview_256x256_rect --random_mask 0
------------ Options -------------
d_cnum: 32
data_file: imgs/paris-streetview_256x256/
dataset: paris_streetview
dataset_path: imgs/paris-streetview_256x256/
date_str: test_20191211-232248
g_cnum: 32
gpu_ids: 0
img_shapes: [256, 256, 3]
load_model_dir: checkpoints/paris-streetview_256x256_rect
mask_shapes: [128, 128]
mask_type: rect
mode: save
model: gmcnn
model_folder: test_20191211-232248_paris_streetview_gmcnn_s256x256_gc32
phase: test
random_mask: False
saving_path: ./test_results\test_20191211-232248_paris_streetview_gmcnn_s256x256_gc32
seed: 1
test_dir: ./test_results
test_num: -1
-------------- End ----------------
The total number of testing images is 4, and we take 4 for test.
configuring model..
initialize network with normal
---------- Networks initialized -------------
GMCNN(
  (EB1): ModuleList(
    (0): Conv2d(4, 32, kernel_size=(7, 7), stride=(1, 1))
    (1): Conv2d(32, 64, kernel_size=(7, 7), stride=(2, 2))
    (2): Conv2d(64, 64, kernel_size=(7, 7), stride=(1, 1))
    (3): Conv2d(64, 128, kernel_size=(7, 7), stride=(2, 2))
    (4): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1))
    (5): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1))
    (6): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), dilation=(2, 2))
    (7): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), dilation=(4, 4))
    (8): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), dilation=(8, 8))
    (9): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), dilation=(16, 16))
    (10): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1))
    (11): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1))
    (12): PureUpsampling()
  )
  (EB2): ModuleList(
    (0): Conv2d(4, 32, kernel_size=(5, 5), stride=(1, 1))
    (1): Conv2d(32, 64, kernel_size=(5, 5), stride=(2, 2))
    (2): Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
    (3): Conv2d(64, 128, kernel_size=(5, 5), stride=(2, 2))
    (4): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1))
    (5): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1))
    (6): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1), dilation=(2, 2))
    (7): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1), dilation=(4, 4))
    (8): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1), dilation=(8, 8))
    (9): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1), dilation=(16, 16))
    (10): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1))
    (11): Conv2d(128, 128, kernel_size=(5, 5), stride=(1, 1))
    (12): PureUpsampling()
    (13): Conv2d(128, 64, kernel_size=(5, 5), stride=(1, 1))
    (14): Conv2d(64, 64, kernel_size=(5, 5), stride=(1, 1))
    (15): PureUpsampling()
  )
  (EB3): ModuleList(
    (0): Conv2d(4, 32, kernel_size=(3, 3), stride=(1, 1))
    (1): Conv2d(32, 64, kernel_size=(3, 3), stride=(2, 2))
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
    (3): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2))
    (4): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
    (5): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
    (6): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), dilation=(2, 2))
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), dilation=(4, 4))
    (8): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), dilation=(8, 8))
    (9): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), dilation=(16, 16))
    (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
    (11): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1))
    (12): PureUpsampling()
    (13): Conv2d(128, 64, kernel_size=(3, 3), stride=(1, 1))
    (14): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
    (15): PureUpsampling()
    (16): Conv2d(64, 32, kernel_size=(3, 3), stride=(1, 1))
    (17): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1))
  )
  (decoding_layers): ModuleList(
    (0): Conv2d(224, 16, kernel_size=(3, 3), stride=(1, 1))
    (1): Conv2d(16, 3, kernel_size=(3, 3), stride=(1, 1))
  )
  (pads): ModuleList(
    (0): ReflectionPad2d((0, 0, 0, 0))
    (1): ReflectionPad2d((1, 1, 1, 1))
    (2): ReflectionPad2d((2, 2, 2, 2))
    (3): ReflectionPad2d((3, 3, 3, 3))
    (4): ReflectionPad2d((4, 4, 4, 4))
    (5): ReflectionPad2d((5, 5, 5, 5))
    (6): ReflectionPad2d((6, 6, 6, 6))
    (7): ReflectionPad2d((7, 7, 7, 7))
    (8): ReflectionPad2d((8, 8, 8, 8))
    (9): ReflectionPad2d((9, 9, 9, 9))
    (10): ReflectionPad2d((10, 10, 10, 10))
    (11): ReflectionPad2d((11, 11, 11, 11))
    (12): ReflectionPad2d((12, 12, 12, 12))
    (13): ReflectionPad2d((13, 13, 13, 13))
    (14): ReflectionPad2d((14, 14, 14, 14))
    (15): ReflectionPad2d((15, 15, 15, 15))
    (16): ReflectionPad2d((16, 16, 16, 16))
    (17): ReflectionPad2d((17, 17, 17, 17))
    (18): ReflectionPad2d((18, 18, 18, 18))
    (19): ReflectionPad2d((19, 19, 19, 19))
    (20): ReflectionPad2d((20, 20, 20, 20))
    (21): ReflectionPad2d((21, 21, 21, 21))
    (22): ReflectionPad2d((22, 22, 22, 22))
    (23): ReflectionPad2d((23, 23, 23, 23))
    (24): ReflectionPad2d((24, 24, 24, 24))
    (25): ReflectionPad2d((25, 25, 25, 25))
    (26): ReflectionPad2d((26, 26, 26, 26))
    (27): ReflectionPad2d((27, 27, 27, 27))
    (28): ReflectionPad2d((28, 28, 28, 28))
    (29): ReflectionPad2d((29, 29, 29, 29))
    (30): ReflectionPad2d((30, 30, 30, 30))
    (31): ReflectionPad2d((31, 31, 31, 31))
    (32): ReflectionPad2d((32, 32, 32, 32))
    (33): ReflectionPad2d((33, 33, 33, 33))
    (34): ReflectionPad2d((34, 34, 34, 34))
    (35): ReflectionPad2d((35, 35, 35, 35))
    (36): ReflectionPad2d((36, 36, 36, 36))
    (37): ReflectionPad2d((37, 37, 37, 37))
    (38): ReflectionPad2d((38, 38, 38, 38))
    (39): ReflectionPad2d((39, 39, 39, 39))
    (40): ReflectionPad2d((40, 40, 40, 40))
    (41): ReflectionPad2d((41, 41, 41, 41))
    (42): ReflectionPad2d((42, 42, 42, 42))
    (43): ReflectionPad2d((43, 43, 43, 43))
    (44): ReflectionPad2d((44, 44, 44, 44))
    (45): ReflectionPad2d((45, 45, 45, 45))
    (46): ReflectionPad2d((46, 46, 46, 46))
    (47): ReflectionPad2d((47, 47, 47, 47))
    (48): ReflectionPad2d((48, 48, 48, 48))
  )
)
[Network GM] Total number of parameters : 12.562 M
-----------------------------------------------
Loading pretrained model from checkpoints/paris-streetview_256x256_rect
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    ourModel.load_networks(getLatest(os.path.join(config.load_model_dir, '*.pth')))
  File "C:\Projects\inpainting_gmcnn\pytorch\util\utils.py", line 84, in getLatest
    return files[sorted(range(len(file_times)), key=lambda x: file_times[x])[-1]]
IndexError: list index out of range

**Comment by MrLassagna** [comment]
This issue is resolved...

**Comment by srishtigoelhike** [comment]
> This issue is resolved...

how was this resolved?
