### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'filters'

### ISSUE THREAD

**Issue by MrLassagna** [shepnerd/inpainting_gmcnn#49]
python test.py --dataset paris_streetview --data_file imgs/paris-streetview_256x256/ --load_model_dir checkpoints/paris-streetview_256x256_rect/ --random_mask 0 --g_cnum  32

Traceback (most recent call last):
  File "test.py", line 37, in <module>
    output = model.evaluate(input_image_tf, input_mask_tf, config=config, reuse=reuse)
  File "C:\Projects\Image_inpainting\net\network.py", line 300, in evaluate
    batch_predict = self.build_generator(im, mask, reuse = reuse)
  File "C:\Projects\Image_inpainting\net\network.py", line 37, in build_generator
    x = conv_7( x_w_mask, filters = cnum, strides = 1, name = b_names[0] + 'conv1' )
TypeError: __init__() got multiple values for argument 'filters'

**Comment by shepnerd** [comment]
It appears you have customized the code. We need more context information to infer which part goes wrong. If your problem still existed, would you share the code (network.py) via email?
