### ISSUE TITLE
Bad results for large masks

### ISSUE THREAD

**Issue by prerna-grg** [shepnerd/inpainting_gmcnn#5]
I tried testing your code on masks of large sizes and the output is quite bad. Any idea for some workaround that can be done for this?

**Comment by shepnerd** [comment]
1. Using a network with more capacity and training it with a large size
mask and more time.
2. If you wanna recover less semantically sensitive regions (e.g.,
grassland, sky, and rocks), you can consider applying contextual attention
module or non-local module to the bottleneck of the generator. They work
well for even large missing regions.
3. If you are using masks generated by stokes, sparse convolution (or
partial convolution) and gated convolution will be helpful. Meanwhile, you
can consider removing adversarial training and replace l1 loss with
perceptual loss.

Prerna Garg <notifications@github.com> 于2019年4月1日周一 下午3:55写道：
