### ISSUE TITLE
Hard-code error

### ISSUE THREAD

**Issue by jinyu121** [shepnerd/inpainting_gmcnn#50]
Here https://github.com/shepnerd/inpainting_gmcnn/blob/512acf3e35e64068e49aff0b51344fd95bd74c33/pytorch/model/net.py#L258 , the code hard-code the final-size of the feature to the Discriminator, 16, which is suitable for input size of 256. But if you are using input size of 512, it should be 32\*32\*some_other_value.

**Comment by shepnerd** [comment]
Thanks for pointing out this error. We will update the corresponding codes soon.
