### ISSUE TITLE
Question about the restoring pretrained model

### ISSUE THREAD

**Issue by Zhong-gy** [shepnerd/inpainting_gmcnn#57]
Hi @shepnerd, thanks for your work!
I'm rather confused about this, the way of reloading the pretained model.
1) https://github.com/shepnerd/inpainting_gmcnn/blob/ba7f7109c38c3805800283cdb9d79cd7c4a3294f/tensorflow/train.py#L39   
       1) saver.restore(sess, tf.train.latest_checkpoint(config.load_model_dir))
2)   https://github.com/shepnerd/inpainting_gmcnn/blob/ba7f7109c38c3805800283cdb9d79cd7c4a3294f/tensorflow/train.py#L40
       2) assign_ops = list( map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)), **g_vars**))
          sess.run(assign_ops)
3)  https://github.com/shepnerd/inpainting_gmcnn/blob/ba7f7109c38c3805800283cdb9d79cd7c4a3294f/tensorflow/test.py#L43
     3) **vars_list** = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
         assign_ops = list(map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)), **vars_list**))
         sess.run(assign_ops)

Is there any difference between 1) , 2) and 3)?
Forgive me for bothering you.

**Comment by shepnerd** [comment]
saver.restore will load all variables, including those from the discriminator. 2) and 3) only load the variables from the generator, and they are just implemented in slightly different ways.

**Comment by Zhong-gy** [comment]
Thanks for your reply! @shepnerd.
But in the process of restoring training, shouldn't all variables be restored(including variables from the discriminator)? 
            **assign_ops = list(
                map(lambda x: tf.assign(x, tf.contrib.framework.load_variable(config.load_model_dir, x.name)), g_vars))**
Is the code above(in train.py)  just for the pretrain_network? After that , for the full model training, you using the code(in train.py)  below to restore?
            **saver.restore(sess, tf.train.latest_checkpoint(config.load_model_dir))**

**Comment by shepnerd** [comment]
Yes, you are right.

**Comment by Zhong-gy** [comment]
Thanks for your enthusiastic reply! @shepnerd.
