### ISSUE TITLE
Bug with pretrained model celebahq_512x512_rect/

### ISSUE THREAD

**Issue by TommyZihao** [shepnerd/inpainting_gmcnn#61]
When I run
python3 painter_gmcnn.py --load_model_dir ./checkpoints/celebahq_512x512_rect/ --img_shapes 512,512 --mode silent

It shows:
ValueError: Dimension 3 in both shapes must be equal, but are 32 and 64. Shapes are [7,7,5,32] and [7,7,5,64]. for 'Assign' (op: 'Assign') with input shapes: [7,7,5,32], [7,7,5,64].

MacOS
All other pre-trained model works fine.

**Comment by shepnerd** [comment]
Try it with one more option that `--g_cnum 64`.

**Comment by qwerdbeta** [comment]
should d_num be set to 64 as well for other reasons such as training?

**Comment by qwerdbeta** [comment]
I tried this and could pretrain but when I try to fine tune, I get this error:

Loading [model]
Loading done.
model setting up..
training initializing..
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    ourModel.optimize_parameters()
  File "G:\pythonAI\inpainting_gmcnn\pytorch\model\net.py", line 332, in optimize_parameters
    self.forward_D()
  File "G:\pythonAI\inpainting_gmcnn\pytorch\model\net.py", line 304, in forward_D
    self.completed_logit, self.completed_local_logit = self.netD(self.completed.detach(), self.completed_local.detach())
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\pythonAI\inpainting_gmcnn\pytorch\model\net.py", line 202, in forward
    x_local = self.local_discriminator(x_l)
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\pythonAI\inpainting_gmcnn\pytorch\model\net.py", line 184, in forward
    self.logit = self.layers[-1](self.embedding)
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "G:\pythonAI\inpainting_gmcnn\pytorch\model\layer.py", line 267, in forward
    return self.module.forward(*input)
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\modules\linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [4 x 12544], m2: [65536 x 1] at c:\a\w\1\s\tmp_conda_3.7_061434\conda\conda-bld\pytorch_1544163540495\work\aten\src\thc\generic/THCTensorMathBlas.cu:266

**Comment by qwerdbeta** [comment]
some more info on the options I am using:

------------ Options -------------
D_max_iters: 5
batch_size: 4
checkpoint_dir: ./checkpoints
d_cnum: 32
data_file: G:\pythonAI\plotly-charts\imgs\filelist.txt
dataset: mySet
dataset_path: G:\pythonAI\plotly-charts\imgs\filelist.txt
date_str: 20200909-151913
epochs: 1
g_cnum: 64
gpu_ids: ['0', '1']
img_shapes: [512, 512, 3]
lambda_adv: 0.001
lambda_ae: 1.2
lambda_gp: 10
lambda_mrf: 0.05
lambda_rec: 1.4
load_model_dir:
lr: 1e-05
margins: [0, 0]
mask_shapes: [256, 256]
mask_type: rect
max_delta_shapes: [32, 32]
model_folder: ./checkpoints\20200909-151913_GMCNN_mySet_b4_s512x512_gc64_dc32_randmask-rect
model_name: GMCNN
padding: SAME
phase: train
pretrain_network: False
random_crop: True
random_mask: True
random_seed: False
spectral_norm: True
train_spe: 500
vgg19_path: vgg19_weights/imagenet-vgg-verydeep-19.mat
viz_steps: 5
-------------- End ----------------
loading data..
data loaded..
configuring model..
initialize network with normal
initialize network with normal

**Comment by qwerdbeta** [comment]
when my net.py file has the line:

class GlobalLocalDiscriminator(BaseNet):
    def __init__(self, in_channels, cnum=32, g_fc_channels=16*16*32*4, l_fc_channels=4 * 4 * 64 * 4, act=F.elu, norm=None,
                 spectral_norm=True):
 
this produces the error:

 File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\modules\linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "G:\pythonAI\Miniconda3\lib\site-packages\torch\nn\functional.py", line 1352, in linear
    ret = torch.addmm(torch.jit._unwrap_optional(bias), input, weight.t())
RuntimeError: size mismatch, m1: [4 x 30720], m2: [32768 x 1] at c:\a\w\1\s\tmp_conda_3.7_061434\conda\conda-bld\pytorch_1544163540495\work\aten\src\thc\generic/THCTensorMathBlas.cu:266

**Comment by qwerdbeta** [comment]
and when it's l_fc_channels=4 * 4 * 32 * 4

the error is also:

RuntimeError: size mismatch, m1: [4 x 30720], m2: [32768 x 1] at c:\a\w\1\s\tmp_conda_3.7_061434\conda\conda-bld\pytorch_1544163540495\work\aten\src\thc\generic/THCTensorMathBlas.cu:266

**Comment by opptimus** [comment]
> Try it with one more option that `--g_cnum 64`.

thanks!
