### ISSUE TITLE
Question about training time 

### ISSUE THREAD

**Issue by cmyyy** [shepnerd/inpainting_gmcnn#7]
@shepnerd ,hello. Thanks for your great work and also looking forward to paper ' Semantic Regeneration Network' .
Since gmcnn has a huge amount of parameters, i wonder how much time you spend on training the model on different dataset?Thx!

**Comment by shepnerd** [comment]
It took around 2/2/10/10/10 days on
streetview/celebA-HQ-256/celebA/places2/imagenet, respectively.

cmyyy <notifications@github.com> 于2019年4月2日周二 上午9:44写道：

**Comment by ljjcoder** [comment]
@shepnerd how long does it cost on stage1(pretrain=1) and stage2(pretrain=2)  respectly?

**Comment by shepnerd** [comment]
Generally, the pretrain stage takes up 30%~40% of the whole training time.
