### ISSUE TITLE
Want to train on a 512-size image, which parameters need to be modified?

### ISSUE THREAD

**Issue by silence1114** [shepnerd/inpainting_gmcnn#8]
@shepnerd  Thanks for your great work. However, when I want to train on 512 size celebahq images, the results are bad. Which parameters need to be modified? I just modified the following parameters:
img_shapes=256
mask_shapes=128
g_cnum=64

And the results are bad.

**Comment by shepnerd** [comment]
You need to set the parameters like the following: "--img_shapes 512,512
--mask_shapes 256,256 --g_cnum 64" when calling train.py in the console. Or
modifying these parameters in train_opinions.py. Note the shapes given here
are in the format of "h,w" or "h,w,c".

silence14 <notifications@github.com> 于2019年4月2日周二 下午5:11写道：
