### ISSUE TITLE
When training on 512-size celeba-hq images

### ISSUE THREAD

**Issue by silence1114** [shepnerd/inpainting_gmcnn#9]
@shepnerd Thank you for your reply. I am very sorry, I made some mistakes in the previous issue. When training on 512-size celeba-hq images.  I modified the following parameters in train_options.py：

self.parser.add_argument('--img_shapes', type=str, default='512,512,3',
                                 help='given shape parameters: h,w,c or h,w')
self.parser.add_argument('--mask_shapes', type=str, default='256,256',
                                 help='given mask parameters: h,w')
self.parser.add_argument('--g_cnum', type=int, default=64,
                                 help='# of generator filters in first conv layer')

But it still not work. Are there any other parameters that need to be modified?

**Comment by shepnerd** [comment]
Thank you for your reminder. First, we need a smaller learning rate
(compared with training 256*256 images) like 1e-5 here. Second, using a
Gaussian kernel with a large window size and more iterations when computing
mask weights, e.g., changing "mask_priority = priority_loss_mask(mask)" to
"mask_priority = priority_loss_mask(mask, hsize=128, sigma=1.0 / 60,
iters=16)" in network.py (L178).

silence14 <notifications@github.com> 于2019年4月2日周二 下午6:02写道：
